[package]
description  = "Structure-preserving URL alias detection and expansion"
edition      = "2024"
license      = "MPL-2.0"
name         = "alurl"
rust-version = "1.85"
version      = "0.1.0"

[workspace]

[dependencies]
unicode-ident = "1"
